ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS pdf_blob BYTEA NULL,
  ADD COLUMN IF NOT EXISTS pdf_media_type VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS pdf_size BIGINT NULL;

ALTER TABLE document_images
  ADD COLUMN IF NOT EXISTS image_blob BYTEA NULL,
  ADD COLUMN IF NOT EXISTS media_type VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS byte_size BIGINT NULL;
