// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/config": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Obtener configuracion saneada",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Guardar configuracion editable",
                "parameters": [
                    {
                        "description": "Configuracion editable",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.editableConfigPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/db/migrations/run": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Ejecutar migraciones pendientes del motor activo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/db/migrations/status": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Estado de migraciones de base de datos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/documents/{id}/images": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Listar imagenes IIIF por documento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/documents/{id}/ocr/jobs": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Inicia una generación OCR híbrida, exhaustiva o solo OCR. Requiere sesión administrativa.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OCR"
                ],
                "summary": "Crear trabajo OCR",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Configuración del trabajo",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.CreateOCRJobRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/services.OCRJob"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/migrations/local-to-db/start": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Iniciar migracion local/ssh a base de datos activa (MySQL/Postgres/MongoDB)",
                "parameters": [
                    {
                        "description": "Origen y scope",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.migrationStartPayload"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/migrations/local-to-db/status": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Estado de migracion local/ssh a base de datos activa (MySQL/Postgres/MongoDB)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/migrations/sources/local/browse": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Explorar directorios locales permitidos para migracion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ruta base a explorar",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/ocr/jobs/{job_id}": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OCR"
                ],
                "summary": "Consultar progreso OCR",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del trabajo",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.OCRJob"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/ocr/jobs/{job_id}/cancel": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OCR"
                ],
                "summary": "Cancelar trabajo OCR",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del trabajo",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.OCRJob"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/ocr/languages": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Obtiene los idiomas reconocidos por Tesseract y los paquetes APT disponibles para instalar. Requiere sesión administrativa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OCR"
                ],
                "summary": "Consultar idiomas OCR del sistema",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.OCRLanguageCatalog"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/ocr/languages/install": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Instala hasta 10 paquetes descubiertos en APT mediante un helper privilegiado restringido y verifica el resultado con Tesseract. Instalar no habilita automáticamente el idioma.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OCR"
                ],
                "summary": "Instalar idiomas OCR",
                "parameters": [
                    {
                        "description": "Idiomas Tesseract",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.InstallOCRLanguagesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.InstallOCRLanguagesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/projects": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Listar proyectos y tenants",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/projects/{key}/sync-tenants": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Consulta el endpoint configurado para el proyecto, normaliza la lista y la persiste en config.yaml.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Sincronizar tenants de un proyecto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Clave del proyecto",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config.ProjectConfig"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/service/restart": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "Valida password sudo y programa reinicio asincrono de project-iiif.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Programar reinicio del servicio",
                "parameters": [
                    {
                        "description": "Password sudo",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.restartServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.restartServiceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/documents": {
            "get": {
                "description": "Lista documentos con filtros opcionales por proyecto y tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documentos"
                ],
                "summary": "Listar documentos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Proyecto",
                        "name": "project",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenant",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PDFDocument"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/documents/upload": {
            "post": {
                "description": "Recibe archivo PDF y crea documento con paginas convertidas.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documentos"
                ],
                "summary": "Subir y convertir PDF",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Archivo PDF",
                        "name": "pdf",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Proyecto",
                        "name": "project",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenant",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 1241,
                        "description": "Ancho maximo de imagen",
                        "name": "max_width",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 1754,
                        "description": "Alto maximo de imagen",
                        "name": "max_height",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 150,
                        "description": "Resolucion de render",
                        "name": "dpi",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "jpg",
                        "description": "Formato de salida (jpg o png)",
                        "name": "format",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "default": 85,
                        "description": "Calidad JPEG",
                        "name": "quality",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PDFDocument"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/documents/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documentos"
                ],
                "summary": "Obtener documento por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PDFDocument"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documentos"
                ],
                "summary": "Eliminar documento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.okMessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/documents/{id}/ocr": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OCR"
                ],
                "summary": "Obtener estado OCR de un documento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.OCRDocumentSummary"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/documents/{id}/ocr/autocomplete": {
            "get": {
                "description": "Sugiere palabras reales del OCR por prefijo. La comparación ignora mayúsculas y acentos, conserva la grafía original y requiere al menos 2 caracteres.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OCR"
                ],
                "summary": "Autocompletar palabras OCR dentro de un documento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Prefijo de palabra (mínimo 2 caracteres)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Máximo de sugerencias (máximo 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.OCRAutocompleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/documents/{id}/ocr/pages/{page}": {
            "get": {
                "description": "Devuelve el texto completo y, cuando existe geometría, palabras con bbox x0/x1/y0/y1 expresado en coordenadas del Canvas IIIF. Los OCR históricos sin geometría continúan con geometry_status=page_only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OCR"
                ],
                "summary": "Obtener OCR y bounding boxes de una página",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Número de página",
                        "name": "page",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.OCRPage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/documents/{id}/ocr/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OCR"
                ],
                "summary": "Buscar texto OCR dentro de un documento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Texto a buscar",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Máximo de resultados",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Desplazamiento",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/iiif/{id}/manifest": {
            "get": {
                "description": "Endpoint de compatibilidad para clientes IIIF Presentation v3.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IIIF"
                ],
                "summary": "Obtener manifiesto IIIF Presentation API v3",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del documento",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Paginas o rangos, por ejemplo 1-3,5",
                        "name": "pages",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.IIIFManifest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ocr/autocomplete": {
            "get": {
                "description": "Sugiere palabras reales del OCR por prefijo. La comparación ignora mayúsculas y acentos, conserva la grafía original y requiere al menos 2 caracteres.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OCR"
                ],
                "summary": "Autocompletar palabras OCR por proyecto, tenant o documento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Prefijo de palabra (mínimo 2 caracteres)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Proyecto",
                        "name": "project",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenant",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ID del documento",
                        "name": "document_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Máximo de sugerencias (máximo 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.OCRAutocompleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ocr/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OCR"
                ],
                "summary": "Buscar texto OCR por proyecto, tenant o documento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Texto a buscar",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Proyecto",
                        "name": "project",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tenant",
                        "name": "tenant",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ID del documento",
                        "name": "document_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Máximo de resultados",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Desplazamiento",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Crea cookie de sesion para rutas administrativas.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Iniciar sesion de dashboard",
                "parameters": [
                    {
                        "description": "Credenciales",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.sessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Elimina cookie de sesion activa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Cerrar sesion",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.sessionResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Devuelve estado de autenticacion actual.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verificar sesion",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.sessionResponse"
                        }
                    }
                }
            }
        },
        "/iiif/3/{identifier}/info.json": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IIIF"
                ],
                "summary": "Obtener info IIIF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identificador IIIF",
                        "name": "identifier",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.IIIFImageInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        },
        "/iiif/3/{identifier}/{region}/{size}/{rotation}/{quality_format}": {
            "get": {
                "produces": [
                    "image/jpeg",
                    "image/png",
                    "image/webp"
                ],
                "tags": [
                    "IIIF"
                ],
                "summary": "Obtener imagen IIIF transformada",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identificador IIIF",
                        "name": "identifier",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Region",
                        "name": "region",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tamano",
                        "name": "size",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rotacion",
                        "name": "rotation",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "quality.format",
                        "name": "quality_format",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.OCRConfig": {
            "type": "object",
            "properties": {
                "artifacts": {
                    "type": "object",
                    "properties": {
                        "gzip": {
                            "type": "boolean"
                        }
                    }
                },
                "auto_after_conversion": {
                    "type": "boolean"
                },
                "candidate_languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "default_mode": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "fallback_languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "language_detection": {
                    "type": "object",
                    "properties": {
                        "enabled": {
                            "type": "boolean"
                        },
                        "max_languages": {
                            "type": "integer"
                        },
                        "min_sample_chars": {
                            "type": "integer"
                        },
                        "minimum_confidence": {
                            "type": "number"
                        },
                        "sample_pages": {
                            "type": "integer"
                        }
                    }
                },
                "language_installation": {
                    "type": "object",
                    "properties": {
                        "enabled": {
                            "type": "boolean"
                        },
                        "helper_path": {
                            "type": "string"
                        },
                        "timeout_seconds": {
                            "type": "integer"
                        }
                    }
                },
                "min_text_chars": {
                    "type": "integer"
                },
                "page_timeout_seconds": {
                    "type": "integer"
                },
                "render_dpi": {
                    "type": "integer"
                },
                "retries_per_page": {
                    "type": "integer"
                },
                "workers": {
                    "type": "integer"
                }
            }
        },
        "config.ProjectConfig": {
            "type": "object",
            "properties": {
                "bulk_upload": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "multitenant": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "tenants": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tenants_auth_header": {
                    "type": "string"
                },
                "tenants_auth_token": {
                    "type": "string"
                },
                "tenants_auth_type": {
                    "type": "string"
                },
                "tenants_endpoint": {
                    "type": "string"
                },
                "tenants_token_configured": {
                    "type": "boolean"
                }
            }
        },
        "handlers.editableConfigPayload": {
            "type": "object",
            "properties": {
                "binary_storage": {
                    "type": "object",
                    "properties": {
                        "mode": {
                            "type": "string"
                        },
                        "temp_path": {
                            "type": "string"
                        }
                    }
                },
                "conversion": {
                    "type": "object",
                    "properties": {
                        "default_format": {
                            "type": "string"
                        },
                        "default_height": {
                            "type": "integer"
                        },
                        "default_quality": {
                            "type": "integer"
                        },
                        "default_width": {
                            "type": "integer"
                        },
                        "dpi": {
                            "type": "integer"
                        },
                        "enable_ocr": {
                            "type": "boolean"
                        }
                    }
                },
                "database": {
                    "type": "object",
                    "properties": {
                        "DB_CONNECTION": {
                            "type": "string"
                        },
                        "DB_DATABASE": {
                            "type": "string"
                        },
                        "DB_HOST": {
                            "type": "string"
                        },
                        "DB_PASSWORD": {
                            "type": "string"
                        },
                        "DB_PORT": {
                            "type": "string"
                        },
                        "DB_USERNAME": {
                            "type": "string"
                        },
                        "auto_migrate": {
                            "type": "boolean"
                        },
                        "mongodb": {
                            "type": "object",
                            "properties": {
                                "auth_source": {
                                    "type": "string"
                                },
                                "database": {
                                    "type": "string"
                                },
                                "direct_connection": {
                                    "type": "boolean"
                                },
                                "host": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                },
                                "port": {
                                    "type": "string"
                                },
                                "server_selection_timeout_ms": {
                                    "type": "integer"
                                },
                                "user": {
                                    "type": "string"
                                }
                            }
                        },
                        "mysql": {
                            "type": "object",
                            "properties": {
                                "charset": {
                                    "type": "string"
                                },
                                "database": {
                                    "type": "string"
                                },
                                "host": {
                                    "type": "string"
                                },
                                "parse_time": {
                                    "type": "boolean"
                                },
                                "password": {
                                    "type": "string"
                                },
                                "port": {
                                    "type": "string"
                                },
                                "user": {
                                    "type": "string"
                                }
                            }
                        },
                        "postgres": {
                            "type": "object",
                            "properties": {
                                "database": {
                                    "type": "string"
                                },
                                "host": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                },
                                "port": {
                                    "type": "string"
                                },
                                "schema": {
                                    "type": "string"
                                },
                                "sslmode": {
                                    "type": "string"
                                },
                                "user": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "frontend": {
                    "type": "object",
                    "properties": {
                        "enabled": {
                            "type": "boolean"
                        },
                        "menu_orientation": {
                            "type": "string"
                        },
                        "password": {
                            "type": "string"
                        },
                        "path": {
                            "type": "string"
                        },
                        "require_auth": {
                            "type": "boolean"
                        },
                        "username": {
                            "type": "string"
                        }
                    }
                },
                "iiif": {
                    "type": "object",
                    "properties": {
                        "api_version": {
                            "type": "string"
                        },
                        "base_url": {
                            "type": "string"
                        },
                        "cache": {
                            "type": "boolean"
                        },
                        "cache_ttl": {
                            "type": "integer"
                        },
                        "max_height": {
                            "type": "integer"
                        },
                        "max_width": {
                            "type": "integer"
                        }
                    }
                },
                "ocr": {
                    "$ref": "#/definitions/config.OCRConfig"
                },
                "projects": {
                    "type": "object",
                    "properties": {
                        "allow_dynamic_tenants": {
                            "type": "boolean"
                        },
                        "default_project": {
                            "type": "string"
                        },
                        "enabled": {
                            "type": "boolean"
                        },
                        "items": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/config.ProjectConfig"
                            }
                        },
                        "require_project": {
                            "type": "boolean"
                        }
                    }
                },
                "s3": {
                    "type": "object",
                    "properties": {
                        "access_key_id": {
                            "type": "string"
                        },
                        "bucket": {
                            "type": "string"
                        },
                        "endpoint": {
                            "type": "string"
                        },
                        "filesystem_disk": {
                            "type": "string"
                        },
                        "region": {
                            "type": "string"
                        },
                        "secret_access_key": {
                            "type": "string"
                        },
                        "use_path_style_endpoint": {
                            "type": "boolean"
                        }
                    }
                },
                "security": {
                    "type": "object",
                    "properties": {
                        "cors_origins": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "enable_auth": {
                            "type": "boolean"
                        },
                        "log_level": {
                            "type": "string"
                        },
                        "max_concurrent_uploads": {
                            "type": "integer"
                        }
                    }
                },
                "server": {
                    "type": "object",
                    "properties": {
                        "mode": {
                            "type": "string"
                        },
                        "port": {
                            "type": "string"
                        }
                    }
                },
                "storage": {
                    "type": "object",
                    "properties": {
                        "backend": {
                            "type": "string"
                        },
                        "data_path": {
                            "type": "string"
                        },
                        "documents_path": {
                            "type": "string"
                        },
                        "images_path": {
                            "type": "string"
                        },
                        "manifests_path": {
                            "type": "string"
                        },
                        "pdfs_path": {
                            "type": "string"
                        },
                        "thumbnails_path": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "handlers.errorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string",
                    "example": "detalle interno"
                },
                "error": {
                    "type": "string",
                    "example": "login requerido"
                }
            }
        },
        "handlers.loginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "CAMBIAR_PASSWORD"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "handlers.migrationStartPayload": {
            "type": "object",
            "properties": {
                "scope": {
                    "$ref": "#/definitions/handlers.migrationStartScope"
                },
                "source": {
                    "$ref": "#/definitions/handlers.migrationStartSource"
                }
            }
        },
        "handlers.migrationStartScope": {
            "type": "object",
            "properties": {
                "project_key": {
                    "type": "string",
                    "example": "metavisor"
                },
                "tenant_key": {
                    "type": "string",
                    "example": "sunat"
                }
            }
        },
        "handlers.migrationStartSource": {
            "type": "object",
            "properties": {
                "local": {
                    "$ref": "#/definitions/handlers.migrationStartSourceLocal"
                },
                "ssh": {
                    "$ref": "#/definitions/handlers.migrationStartSourceSSH"
                },
                "type": {
                    "type": "string",
                    "example": "local"
                }
            }
        },
        "handlers.migrationStartSourceLocal": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "example": "/var/lib/project_iiif"
                }
            }
        },
        "handlers.migrationStartSourceSSH": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string",
                    "example": "172.21.227.83"
                },
                "path": {
                    "type": "string",
                    "example": "/var/lib/project_iiif"
                },
                "port": {
                    "type": "integer",
                    "example": 2230
                },
                "private_key": {
                    "type": "string",
                    "example": "-----BEGIN OPENSSH PRIVATE KEY-----"
                },
                "user": {
                    "type": "string",
                    "example": "robison"
                }
            }
        },
        "handlers.okMessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "handlers.restartServiceRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "tu_password_sudo"
                }
            }
        },
        "handlers.restartServiceResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "message": {
                    "type": "string",
                    "example": "reinicio programado; el servicio se reiniciara en breve"
                },
                "ok": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handlers.sessionResponse": {
            "type": "object",
            "properties": {
                "authenticated": {
                    "type": "boolean",
                    "example": true
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "models.IIIFAnnotation": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/models.IIIFBody"
                },
                "id": {
                    "type": "string"
                },
                "motivation": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.IIIFAnnotationPage": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IIIFAnnotation"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.IIIFBody": {
            "type": "object",
            "properties": {
                "format": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "service": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IIIFService"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.IIIFCanvas": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IIIFAnnotationPage"
                    }
                },
                "label": {},
                "type": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "models.IIIFImageInfo": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "profile": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "sizes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IIIFSize"
                    }
                },
                "tiles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IIIFTile"
                    }
                },
                "type": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "models.IIIFManifest": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IIIFCanvas"
                    }
                },
                "label": {},
                "type": {
                    "type": "string"
                }
            }
        },
        "models.IIIFService": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "profile": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.IIIFSize": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "models.IIIFTile": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "scaleFactors": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "models.PDFDocument": {
            "type": "object",
            "properties": {
                "conversionDpi": {
                    "type": "integer"
                },
                "conversionFormat": {
                    "type": "string"
                },
                "conversionHeight": {
                    "type": "integer"
                },
                "conversionQuality": {
                    "type": "integer"
                },
                "conversionWidth": {
                    "type": "integer"
                },
                "convertedPages": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "manifestUrl": {
                    "type": "string"
                },
                "migratedFromLocal": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "outline": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PDFOutlineItem"
                    }
                },
                "projectKey": {
                    "type": "string"
                },
                "status": {
                    "description": "processing, completed, error",
                    "type": "string"
                },
                "tenantKey": {
                    "type": "string"
                },
                "thumbnailUrl": {
                    "type": "string"
                },
                "totalPages": {
                    "type": "integer"
                },
                "uploadDate": {
                    "type": "string"
                }
            }
        },
        "models.PDFOutlineItem": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "integer"
                },
                "pageNumber": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "services.CreateOCRJobRequest": {
            "type": "object",
            "properties": {
                "force": {
                    "type": "boolean"
                },
                "language_mode": {
                    "type": "string"
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mode": {
                    "type": "string"
                }
            }
        },
        "services.InstallOCRLanguagesRequest": {
            "type": "object",
            "required": [
                "languages"
            ],
            "properties": {
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "deu",
                        "ita"
                    ]
                }
            }
        },
        "services.InstallOCRLanguagesResponse": {
            "type": "object",
            "properties": {
                "catalog": {
                    "$ref": "#/definitions/services.OCRLanguageCatalog"
                },
                "installed": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "services.OCRAutocompleteItem": {
            "type": "object",
            "properties": {
                "frequency": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "services.OCRAutocompleteResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.OCRAutocompleteItem"
                    }
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "services.OCRBoundingBox": {
            "type": "object",
            "properties": {
                "x0": {
                    "type": "integer",
                    "example": 940
                },
                "x1": {
                    "type": "integer",
                    "example": 1016
                },
                "y0": {
                    "type": "integer",
                    "example": 1543
                },
                "y1": {
                    "type": "integer",
                    "example": 1557
                }
            }
        },
        "services.OCRDocumentSummary": {
            "type": "object",
            "properties": {
                "active_generation": {
                    "type": "string"
                },
                "document_id": {
                    "type": "string"
                },
                "failed_pages": {
                    "type": "integer"
                },
                "indexed_pages": {
                    "type": "integer"
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "project_key": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tenant_key": {
                    "type": "string"
                },
                "total_pages": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "services.OCRJob": {
            "type": "object",
            "properties": {
                "cancel_requested": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "current_page": {
                    "type": "integer"
                },
                "document_id": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "failed_pages": {
                    "type": "integer"
                },
                "finished_at": {
                    "type": "string"
                },
                "generation": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "language_mode": {
                    "type": "string"
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mode": {
                    "type": "string"
                },
                "processed_pages": {
                    "type": "integer"
                },
                "project_key": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tenant_key": {
                    "type": "string"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "services.OCRLanguage": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "deu"
                },
                "detection_supported": {
                    "type": "boolean",
                    "example": true
                },
                "enabled": {
                    "type": "boolean",
                    "example": false
                },
                "installed": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "Alemán"
                },
                "package": {
                    "type": "string",
                    "example": "tesseract-ocr-deu"
                }
            }
        },
        "services.OCRLanguageCatalog": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.OCRLanguage"
                    }
                },
                "installation_enabled": {
                    "type": "boolean"
                },
                "installed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.OCRLanguage"
                    }
                }
            }
        },
        "services.OCRPage": {
            "type": "object",
            "properties": {
                "canvas_v2": {
                    "type": "string"
                },
                "canvas_v3": {
                    "type": "string"
                },
                "confidence": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "document_id": {
                    "type": "string"
                },
                "engine": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "generation": {
                    "type": "string"
                },
                "geometry_error": {
                    "type": "string"
                },
                "geometry_space": {
                    "type": "string"
                },
                "geometry_status": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "iiif_image": {
                    "type": "string"
                },
                "image_id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "native_text": {
                    "type": "string"
                },
                "ocr_image_height": {
                    "type": "integer"
                },
                "ocr_image_width": {
                    "type": "integer"
                },
                "ocr_text": {
                    "type": "string"
                },
                "page_number": {
                    "type": "integer"
                },
                "schema_version": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                },
                "words": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.OCRWord"
                    }
                }
            }
        },
        "services.OCRWord": {
            "type": "object",
            "properties": {
                "bbox": {
                    "$ref": "#/definitions/services.OCRBoundingBox"
                },
                "confidence": {
                    "type": "number",
                    "example": 95.20067596435548
                },
                "text": {
                    "type": "string",
                    "example": "SÁNCHEZ,"
                }
            }
        }
    },
    "securityDefinitions": {
        "SessionCookie": {
            "type": "apiKey",
            "name": "project_iiif_session",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "IIIF PDF Server API",
	Description:      "API publica unificada: gestion documental v1 e interoperabilidad IIIF Image/Presentation API 3. Las rutas heredadas permanecen operativas pero no se anuncian en esta documentacion.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
